[2023-05-05T11:31:37.214+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into scheduled__2023-05-04T00:00:00+00:00 [queued]>
[2023-05-05T11:31:37.220+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into scheduled__2023-05-04T00:00:00+00:00 [queued]>
[2023-05-05T11:31:37.220+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 6
[2023-05-05T11:31:37.228+0000] {taskinstance.py:1350} INFO - Executing <Task(PostgresOperator): insert_into> on 2023-05-04 00:00:00+00:00
[2023-05-05T11:31:37.232+0000] {standard_task_runner.py:57} INFO - Started process 736 to run task
[2023-05-05T11:31:37.235+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into', 'scheduled__2023-05-04T00:00:00+00:00', '--job-id', '1125', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp5d_w5l59']
[2023-05-05T11:31:37.237+0000] {standard_task_runner.py:85} INFO - Job 1125: Subtask insert_into
[2023-05-05T11:31:37.280+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into scheduled__2023-05-04T00:00:00+00:00 [running]> on host 39440b36e721
[2023-05-05T11:31:37.317+0000] {abstractoperator.py:582} ERROR - Exception rendering Jinja template for task 'insert_into', field 'sql'. Template: "\n            INSERT INTO dag_runs (dt, dag_id) VALUES ('{{ dt }}', '{{dag.dag_id}}')\n        "
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 574, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 539, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 14, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dt' is undefined
[2023-05-05T11:31:37.319+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1430, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1554, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2202, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 574, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 539, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 14, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dt' is undefined
[2023-05-05T11:31:37.328+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v02, task_id=insert_into, execution_date=20230504T000000, start_date=20230505T113137, end_date=20230505T113137
[2023-05-05T11:31:37.335+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1125 for task insert_into ('dt' is undefined; 736)
[2023-05-05T11:31:37.368+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-05T11:31:37.382+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
